name: Build and Deploy

on:
  workflow_run:
    workflows: ["Trigger Repo B on Build Success"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to your desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build  # Replace with your build script/command

    - name: Deploy to Production
      run: |
        # Add your deployment commands here
        # Example: Deploy to a web server or cloud platform

