# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on completion status of github-cross-repo-reployment-repo-a repo
  workflow_run:
    workflows: ["CI-github-cross-repo-reployment-repo-a"]
    types:
      - repo-a-deployment-tagged

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

       # Add your deployment steps here for RepoB, using the TAG from RepoA.
      - name: Deploy RepoB
        # Add your deployment steps here for RepoB, using the TAG from RepoA.
        run: |
          # Your deployment commands here
          # Example: npm install && npm build && npm deploy --tag $TAG
        env:
          TAG: ${{ github.event.client_payload.tag }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Angular version

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build  # Adjust the build command as per your Angular app

      - name: Deploy to Hosting
        run: |
          # Add your deployment commands here
          run: echo Completed!!!
          env:
          TAG: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.TAG }}
