name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: durrello
          repo: github-cross-repo-reployment-repo-a
          github_token: ${{ secrets.REPO_A_TOKEN }}
          workflow_file_name: github-cross-repo-reployment-repo-a.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
