name: Custom Release Workflow

on:
  repository_dispatch:
    types:
      - trigger-release-in-b # This should match the event_type you used in the trigger step

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          token: ${{ secrets._GITHUB_TOKEN }}

    - name: Git pull
      run: git pull --prune

    - name: Fetch current tags
      run: git fetch --tags
    
    - name: Determine the next version number
      id: determine_version
      run: |
        current_date=$(date +'%Y%m%d')
        current_tag="prod$current_date.0"
        
        last_version=$(git tag --list "$current_tag.*" | sort -rV | head -n 1)
        
        if [ -n "$last_version" ]; then
          last_version=${last_version##*.}
          next_version=$((last_version + 1))
          next_tag="prod$current_date.$next_version"
        else
          next_tag=$current_tag
        fi
        
        echo "Creating new tag $next_tag."
        echo "$next_tag" >> tag.txt
      shell: bash
      
    - name: Read release tag
      id: read_tag
      run: echo "::set-output name=tag::$(cat tag.txt)"
      shell: bash

    - name: Create and push release tag
      run: |
        git tag ${{ steps.read_tag.outputs.tag }}
        git push --tags
      if: steps.read_tag.outputs.tag != ''
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ''
        tag_name: ${{ steps.read_tag.outputs.tag }}
        title: Release ${{ steps.read_tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
